export const PLUS = '/assets/icon/plus.svg'
export const SORT = '/assets/icon/sort.svg'
export const TRASH = '/assets/icon/trash.svg'
export const WARNING = '/assets/icon/warning.svg'
export const SUCCESS = '/assets/icon/success.svg'
export const CLOSE = '/assets/icon/close.svg'
export const OPEN = '/assets/icon/open.svg'